"""empty message

Revision ID: 1f8e775a9cd
Revises: None
Create Date: 2015-02-22 15:40:21.653168

"""

# revision identifiers, used by Alembic.
revision = '1f8e775a9cd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
